#ifndef LEONOS_UAPI_LINUX_MMAN_H
#define LEONOS_UAPI_LINUX_MMAN_H

/* Linux v6.12 native x86-64 mmap/mprotect wire flags. */
#define LINUX_PROT_NONE 0x0u
#define LINUX_PROT_READ 0x1u
#define LINUX_PROT_WRITE 0x2u
#define LINUX_PROT_EXEC 0x4u
#define LINUX_MAP_SHARED 0x01u
#define LINUX_MAP_PRIVATE 0x02u
#define LINUX_MAP_SHARED_VALIDATE 0x03u
#define LINUX_MAP_FIXED 0x10u
#define LINUX_MAP_ANONYMOUS 0x20u
#define LINUX_MAP_NORESERVE 0x4000u
#define LINUX_MAP_STACK 0x20000u
#define LINUX_MAP_FIXED_NOREPLACE 0x100000u

#define LINUX_MREMAP_MAYMOVE 0x1u
#define LINUX_MREMAP_FIXED   0x2u

#define LINUX_MCL_CURRENT 1u
#define LINUX_MCL_FUTURE  2u
#define LINUX_MCL_ONFAULT 4u
#define LINUX_MLOCK_ONFAULT 1u

#define LINUX_MS_ASYNC      1u
#define LINUX_MS_INVALIDATE 2u
#define LINUX_MS_SYNC       4u

#define LINUX_MADV_NORMAL       0
#define LINUX_MADV_RANDOM       1
#define LINUX_MADV_SEQUENTIAL   2
#define LINUX_MADV_WILLNEED     3
#define LINUX_MADV_DONTNEED     4
#define LINUX_MADV_FREE         8
#define LINUX_MADV_DONTFORK     10
#define LINUX_MADV_DOFORK       11
#define LINUX_MADV_MERGEABLE    12
#define LINUX_MADV_UNMERGEABLE  13
#define LINUX_MADV_HUGEPAGE     14
#define LINUX_MADV_NOHUGEPAGE   15
#define LINUX_MADV_DONTDUMP     16
#define LINUX_MADV_DODUMP       17
#define LINUX_MADV_WIPEONFORK   18
#define LINUX_MADV_KEEPONFORK   19
#define LINUX_MADV_COLD         20
#define LINUX_MADV_PAGEOUT      21
#define LINUX_MADV_POPULATE_READ 22
#define LINUX_MADV_POPULATE_WRITE 23
#define LINUX_MADV_DONTNEED_LOCKED 24

#endif
