# Kernel UAPI export (headers_install).
#
# The whitelist in configs/header-export.list is the single source of truth
# for what leaves the kernel's UAPI tree. Files are published through
# leonos-emit (content-change-only), so an unchanged export never retouches
# mtimes and never rebuilds userland objects; a header removed from the list
# is pruned from the export on the next install. tools/test_header_export.py
# enforces the exact set, self-contained compilation and the absence of
# private includes.

HEADER_EXPORT_LIST ?= $(LEONOS_SRC)/configs/header-export.list
HEADER_EXPORT_ROOT := $(O)/kernel-export
HEADER_EXPORT_INCLUDE := $(HEADER_EXPORT_ROOT)/include
HEADER_EXPORT_MANIFEST := $(HEADER_EXPORT_ROOT)/manifest.txt

HEADER_EXPORT_ENTRIES := $(shell sed -e 's/\#.*//' -e '/^[[:space:]]*$$/d' $(HEADER_EXPORT_LIST))
HEADER_EXPORT_SOURCES := $(addprefix $(LEONOS_SRC)/,$(HEADER_EXPORT_ENTRIES))
HEADER_EXPORT_INSTALLED := $(addprefix $(HEADER_EXPORT_INCLUDE)/,$(patsubst include/uapi/%,%,$(HEADER_EXPORT_ENTRIES)))

$(HEADER_EXPORT_MANIFEST): $(HEADER_EXPORT_SOURCES) $(HEADER_EXPORT_LIST) $(LEONOS_EMIT)
	$(call LEONOS_LOG,INSTALL,$(HEADER_EXPORT_INCLUDE))
	$(Q)set -eu; \
	mkdir -p '$(HEADER_EXPORT_INCLUDE)'; \
	for entry in $(HEADER_EXPORT_ENTRIES); do \
	    case "$$entry" in \
	    include/uapi/*) rel=$${entry#include/uapi/} ;; \
	    *) echo "headers_install: $$entry: not under include/uapi/" >&2; exit 1 ;; \
	    esac; \
	    test -f "$(LEONOS_SRC)/$$entry" || { echo "headers_install: $$entry: missing" >&2; exit 1; }; \
	    mkdir -p "$(HEADER_EXPORT_INCLUDE)/$$(dirname "$$rel")"; \
	    cp "$(LEONOS_SRC)/$$entry" "$(HEADER_EXPORT_INCLUDE)/$$rel.tmp"; \
	    $(LEONOS_EMIT) --input "$(HEADER_EXPORT_INCLUDE)/$$rel.tmp" --output "$(HEADER_EXPORT_INCLUDE)/$$rel"; \
	    rm -f "$(HEADER_EXPORT_INCLUDE)/$$rel.tmp"; \
	done; \
	{ printf '%s\n' '# generated by headers_install; source: configs/header-export.list'; \
	  for entry in $(HEADER_EXPORT_ENTRIES); do printf '%s\n' "$${entry#include/uapi/}"; done; \
	} | LC_ALL=C sort > '$(HEADER_EXPORT_MANIFEST).tmp'; \
	$(LEONOS_EMIT) --input '$(HEADER_EXPORT_MANIFEST).tmp' --output '$(HEADER_EXPORT_MANIFEST)'; \
	rm -f '$(HEADER_EXPORT_MANIFEST).tmp'; \
	find '$(HEADER_EXPORT_INCLUDE)' -type f -printf '%P\n' | LC_ALL=C sort > '$(HEADER_EXPORT_ROOT)/present.tmp'; \
	sed -e '/^#/d' -e '/^[[:space:]]*$$/d' '$(HEADER_EXPORT_MANIFEST)' | LC_ALL=C sort > '$(HEADER_EXPORT_ROOT)/want.tmp'; \
	comm -23 '$(HEADER_EXPORT_ROOT)/present.tmp' '$(HEADER_EXPORT_ROOT)/want.tmp' \
	  | (cd '$(HEADER_EXPORT_INCLUDE)' && xargs -r rm -f); \
	rm -f '$(HEADER_EXPORT_ROOT)/present.tmp' '$(HEADER_EXPORT_ROOT)/want.tmp'; \
	find '$(HEADER_EXPORT_INCLUDE)' -mindepth 1 -type d -empty -delete

.PHONY: headers_install
headers_install: $(HEADER_EXPORT_MANIFEST)
