#!/bin/sh
# PWeb PHP-CGI shim.
#
# PWeb execs `cgi_pass /bin/sh <this-shim>` with the standard CGI env:
# GATEWAY_INTERFACE REQUEST_METHOD SCRIPT_NAME QUERY_STRING REMOTE_ADDR
# REMOTE_PORT CONTENT_LENGTH CONTENT_TYPE HTTP_* PWEB_ROOT PWEB_CGI_DISK
# The on-disk target path is also argv[1] (PWEB_CGI_DISK mirrors it).
#
# The shim locates the system `php` CLI and runs a generated bootstrap
# (in /tmp, not under the web root) that populates $_GET from
# QUERY_STRING, $_POST from the spooled request body, and $_SERVER from
# the CGI env, then require()s the user's script -- so full superglobal
# semantics work without a php-cgi SAPI build.

set -u

# --- locate the PHP binary ------------------------------------------------
# PWEB_PHP_BIN overrides; otherwise search well-known absolute paths
# (a CGI child inherits the server's env, whose PATH may be truncated).
BIN="${PWEB_PHP_BIN:-}"
if [ -z "$BIN" ]; then
    for cand in /usr/bin/php /usr/local/bin/php /opt/php/bin/php \
                /usr/bin/php8.5 /usr/bin/php8.4 /usr/bin/php8.3; do
        if [ -x "$cand" ]; then BIN="$cand"; break; fi
    done
    if [ -z "$BIN" ]; then
        BIN="$(command -v php 2>/dev/null || echo php)"
    fi
fi

# --- resolve the on-disk script -------------------------------------------
# Prefer PWeb's normalized absolute path (PWEB_CGI_DISK / argv[1]);
# fall back to PWEB_ROOT + SCRIPT_NAME.
DISK="${PWEB_CGI_DISK:-${1:-}}"
if [ -z "$DISK" ]; then
    ROOT="${PWEB_ROOT:-/}"
    SCRIPT="${SCRIPT_NAME:-/}"
    DISK="${ROOT}${SCRIPT}"
fi

# PWeb's request body arrives on stdin. PWeb closes its side of the pipe
# after writing, so `cat` returns as soon as the body is complete
# (immediately on GET).
if [ "${CONTENT_LENGTH:-0}" != "0" ]; then
    BODY_FILE="/tmp/.pweb_php_body$$"
    cat > "$BODY_FILE" 2>/dev/null || BODY_FILE=""
else
    BODY_FILE=""
fi

# --- respond 404 if the file does not exist under the root -----------------
if [ ! -f "$DISK" ]; then
    [ -n "${BODY_FILE:-}" ] && rm -f "$BODY_FILE"
    printf 'Status: 404 Not Found\r\nContent-Type: text/plain\r\n\r\n'
    printf '404 Not Found: %s\n' "$DISK"
    exit 0
fi

# --- emit response headers (PHP appends its body to stdout) ----------------
# HTTP must use CRLF line endings; \n causes clients to reject the header.
printf 'Content-Type: text/html\r\n\r\n'

# --- bootstrap: bridge the CGI env onto the CLI before the user script ------
BOOT="/tmp/.pweb_php_boot$$"
trap 'rm -f "$BOOT"' EXIT
[ -n "${BODY_FILE:-}" ] && trap 'rm -f "$BOOT" "$BODY_FILE"' EXIT

export BODY_FILE="${BODY_FILE:-}"

# Unquoted PHPEOF on purpose: $BODYFILE expands; \$ keeps PHP literal.
cat > "$BOOT" <<PHPEOF
<?php
/* PWeb PHP bootstrap: populate superglobals from the CGI env, then run the
 * user script. Generated by tools/php-cgi-shim.sh; do not edit. */
error_reporting(E_ALL);
ini_set("display_errors", "1");
ini_set("session.save_path", "/tmp");

\$disk = \$argv[1];
\$spool = getenv("BODY_FILE");

/* --- \$_GET from QUERY_STRING --- */
\$qs = getenv("QUERY_STRING");
if (\$qs) { parse_str(\$qs, \$_GET); }

/* --- \$_POST: form body spooled by the shim --- */
if (\$spool && is_file(\$spool)) {
    \$raw = file_get_contents(\$spool);
    if (\$raw !== false && \$raw !== "") {
        \$ct = getenv("CONTENT_TYPE");
        if (\$ct && stripos(\$ct, "application/x-www-form-urlencoded") !== false) {
            parse_str(\$raw, \$_POST);
        } else {
            \$_POST["__raw"] = \$raw;
        }
    }
}

/* --- \$_SERVER: merge CLI-provided SERVER with the CGI env PWeb set up --- */
\$env = [];
foreach (\$_SERVER as \$k => \$v) { \$env[\$k] = \$v; }
\$env["QUERY_STRING"]      = \$qs;
\$env["REQUEST_METHOD"]    = getenv("REQUEST_METHOD");
\$env["CONTENT_LENGTH"]    = getenv("CONTENT_LENGTH");
\$env["CONTENT_TYPE"]      = getenv("CONTENT_TYPE");
\$env["SERVER_SOFTWARE"]   = "PWeb";
\$env["GATEWAY_INTERFACE"] = "CGI/1.1";
\$env["REMOTE_ADDR"]       = getenv("REMOTE_ADDR");
\$env["HTTP_HOST"]         = getenv("HTTP_HOST");
\$env["SCRIPT_FILENAME"]   = \$disk;
\$env["SCRIPT_NAME"]       = getenv("SCRIPT_NAME");
\$_SERVER = \$env;

/* --- run the user's script; it sees \$_GET/\$_POST/\$_SERVER ready --- */
require \$disk;
PHPEOF

# PWEB_PHP_ARGS lets operators add extra -d options; defaults enable
# error display and EGPCS variable order.
PHP_ARGS="${PWEB_PHP_ARGS:--d display_errors=1 -d variables_order=EGPCS}"
# shellcheck disable=SC2086  # word-splitting of PHP_ARGS is intentional
"$BIN" $PHP_ARGS "$BOOT" "$DISK"
rc=$?
# The EXIT trap already removes the spool; this is a belt-and-suspenders
# for the case where the trap did not run (SIGKILL etc.).
[ -n "${BODY_FILE:-}" ] && rm -f "$BODY_FILE"
exit "$rc"
